// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef MaskColorCheckerGUI_h
#define MaskColorCheckerGUI_h
#include <FL/Fl.H>
#include "Canvas.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *g_overlapSpinner;
extern Fl_Spinner *g_colorsPerTileSpinner;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *g_solidFillCheckButton;
#include <FL/Fl_Button.H>
extern Fl_Button *g_badTileFillColorButton;
#include <FL/Fl_Output.H>
extern Fl_Output *g_maskPathOutput;
extern Fl_Button *g_loadMaskButton;
extern Fl_Button *g_checkButton;
extern Fl_Button *g_saveOutputButton;
#include <FL/Fl_Box.H>
extern Fl_Button *g_gridColorButton;
extern Fl_Check_Button *g_drawGridCheckButton;
extern Fl_Box *g_parametersStatusBox;
#include <FL/Fl_Choice.H>
extern Fl_Choice *g_tileSizeChoice;
extern Fl_Spinner *g_tilesInRowSpinner;
extern Fl_Button *g_fixButton;
extern Fl_Button *g_saveGridButton;
extern Canvas *g_canvas;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *g_menuBar;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_g_menuBar[];
#define g_projectMenu (menu_g_menuBar+0)
#define g_menuItemSave (menu_g_menuBar+2)
#define g_menuItemSaveAs (menu_g_menuBar+3)
#endif
